### PR TITLE
Allow greater php versions

### LINKED ISSUE #1: Allow php > 7
Right now, your composer.json file locks the php version to be 7 (using `^7`). It should also allow greater versions, so I'd say change that `^`  with a `>`.

### PR DESCRIPTION
**Pull request by elboletaire**
Closes #1

### CODE REVIEW

**Comment by elboletaire** [comment]
Changed to be `>=` instead of just `>`, because version 7.2 should be also included (it wasn't with `>`)

**Comment by elboletaire** [comment]
sorry @eclyptox, should you tell packagist somehow that the package has been updated? It's been a while since I used composer for the last time, but I recall something else should be done, like creating a tag or something like that (?)

rn trying to install the package still waits for php ^7 instead of >=7 as specified in my change.

Edit: using `@dev` obviously returns the latest version, so I guess it's just a tagging issue.

**Comment by eclyptox** [comment]
I have published a new release. Try now. @elboletaire

**Comment by elboletaire** [comment]
It works great now, thanks 😄

**Pull request merged**
